global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
        labels:
          application: 'eureka Service Application'


  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          application: 'Notification Service Application'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8082' ]
        labels:
          application: 'inventory Service Application'